matrix:
- name: Markdown
  aspell:
    lang: en
    ignore-case: true
  dictionary:
    wordlists:
    - website/.spellcheck-wordlist.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
      markdown_extensions:
      - pymdownx.superfences
  - pyspelling.filters.html:
      comments: false
      ignores:
      - ':matches(code, pre)'
      - code
      - pre
      - 'blockquote'
  sources:
  - 'website/**/*.md'
  default_encoding: utf-8
