name: Check Broken Links

on:
  pull_request:
    branches:
      - current
    types:
      # runs when the PR is opened
      - opened
      - reopened

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      # checks all markdown files from /docs including all subfolders
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
        folder-path: 'website/'
        check-modified-files-only: 'yes'
        base-branch: 'current'
