name: Content Governance
on: 
  push:
    # Only run if markdown file changes are detected 
    paths:
    - '**.md'

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    # The checkout step
    - uses: actions/checkout@v3
    - uses: rojopolis/spellcheck-github-actions@v0
      name: Spellcheck
      with:
        config_path: website/.spellcheck.yml
