name: Check Markdown links

on: [pull_request]

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Link Checker
        uses: lycheeverse/lychee-action@master
        with:
          args: --verbose --no-progress './website/**/*.md'
      #- name: Run Link Checker
      #  uses: gaurav-nelson/github-action-markdown-link-check@v1
      #  with:
      #    use-verbose-mode: 'yes'
      #    check-modified-files-only: 'yes'
      #    base-branch: 'current'
      #    folder-path: 'website/'
      #    config-file: '.github/workflows/link_checker_config.json'
